version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./../number_converter:/var/www/number_converter
    tty: true
    ports:
      - "7000:7000"
    expose:
      - "7000"
    command:
      - symfony server:start --port=7000
